version: '2'
services:
  postgres:
    image: postgres:9.6
    ports: 
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  
  redis:
    image: redis:3.2
    command: redis-server
    ports:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  
  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/kciweather'
    env_file:
      - '.env'

volumes:
  redis:
  postgres: