
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 
  host: postgres
  port: 5432

development:
  <<: *default
  database: kciweather_development

test:
  <<: *default
  database: kciweather_test

production:
  <<: *default
  database: kciweather_production
  #username: kciwheather
  #password: <%= ENV['KCIWHEATHER_DATABASE_PASSWORD'] %>
